---
set_hostname:
    - ip: 10.1.10.1
      hostname: net10-node1
    - ip: 10.1.10.2
      hostname: net10-node2
    - ip: 10.1.10.3
      hostname: net10-node3
    - ip: 10.1.20.1
      hostname: net20-node1
    - ip: 10.1.20.2
      hostname: net20-node2
    - ip: 10.1.20.3
      hostname: net20-node3
    - ip: 10.1.30.1
      hostname: net30-node1
    - ip: 10.1.30.2
      hostname: net30-node2
    - ip: 10.1.30.3
      hostname: net30-node3
    - ip: 10.1.30.4
      hostname: net30-node4
